---
title: "Cane Toad Invasion"
---

[More information about cane toads in Florida](https://www.smithsonianmag.com/smart-news/plague-invasive-cane-toads-overruns-florida-community-180971797/)

This map shows the spread of cane toads through time in Australia. It uses information from [GBIF](http://www.gbif.org).


```{r, echo=FALSE, cache=FALSE, include=FALSE}
source("R/packages.R")
source("R/functions.R")
```

```{r, cache = TRUE, echo=FALSE, include=FALSE}
  locations <- GetCaneToadLocations(stateProvince="Florida")
  locations$year <- as.integer(locations$year)
  locations <- locations[which(locations$year>=1934),]
```

```{r, cache = TRUE, echo=FALSE, message=FALSE, warning=FALSE}
fla <- ggplot2::map_data("state", "Florida")
#my_map <- ggplot() + geom_polygon(data = fla, aes(x=long, y = lat, group = group)) + coord_fixed(1.3) + geom_point(data=locations, aes(x=locations$decimalLongitude, y=locations$decimalLatitude), col=rgb(1,0,0,0.4)) + labs(title = 'Year: {frame_time}') + transition_time(year) + ease_aes('linear') + shadow_mark() + theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank())
my_map <- ggplot() + geom_polygon(data = fla, aes(x=long, y = lat, group = group)) + coord_fixed(1.3) + geom_point(data=locations, aes(x=locations$decimalLongitude, y=locations$decimalLatitude), col=rgb(1,0,0,0.4)) + labs(title = 'Year: {frame_time}') + transition_time(year) + shadow_mark() + theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank())

animate(my_map, fps=4)
```
